Monday October 07, 2019

9:50::

Requested db links be added to other bl6n databases for my
test user database.

10:00::

Scrum

10:40::

Looking at queries to verify that there are none that deal
in both sequences and genes.

11:40::

Lunch

12:30::

Tested sequence queries on CryptoDB bl6n

1:00::

Continued examining queries

1:50::

Began reworking XML gene queries to use the geneid table.

2:15::

Debugging gene query modification, getting different result
count from the original, not sure which query is 'wrong'.

2:20::

Diffing query results...
Probably need to rebuild the mappedcomment view.

2:20::

Researching oracle materialized view rebuild command.

2:30::

View is not materialized...
Continuing to debug query.

2:40::

Moved inner join, diffs should not be wildly different
anymore.

2:45::

Still appears to be a comment-count difference, but it's
seemingly random now.

Also result count difference is still present (ofc)

2:55::

Making export of diff based on count

3:20::

Cleaned up comments with duplicate link records
(comment.stable_id = link.stable_id).
+
[source, sql]
----

DELETE FROM
  userlogins5.commentstableid
WHERE
  comment_stable_id IN (
    SELECT
      b.comment_stable_id
    FROM
      userlogins5.comments a
      INNER JOIN userlogins5.commentstableid b
        ON a.comment_id = b.comment_id
        AND a.stable_id = b.stable_id
    WHERE
      a.is_visible = 1
  )
----
