= Wednesday October 02, 2019

10:15::

Scrum

11:00::

Sorting out email

11:15::

Syncing repos, catching up on slack, setting up workspace to
continue where i left off yesterday

11:30::

lunch

12:40::

verifying query that would be used by a migrator to remove
the outdated related links from the user database
`userlogins5.commentstableid` table.

12:50::

assisted Danica with getting started with git

13:10::

continued working on query, getting results that i don't
quite understand, 2 queries that should return the same
count are returning 3 rows off from each other.  Getting a
comparable resultset is going to be difficult

13:30::

Encountered error from oracle while attempting to
run half of my test query.
+
.Oracle Error
[code]
----
[2019-10-02 13:30:15] [08000][17410] No more data to read from socket
----

13:37::

Issue appears to be a known Oracle JDBC driver bug, will
attempt switching to the Oracle SQL client to see if the
problem persists there.

13:37::

Setup new connection on oracle sql developer

13:40::

investigating how to use parametrized queries in
sqldeveloper

13:45::

gave up on parametrized queries in sql developer

13:50::

gave up on sql developer, lacks too many features

13:55::

Confirmed that the comment-to-commentstableid `WITH` query
is returning the expected results.

14:11::

Found source of the 3 row discrepancy, there are 3 comments
that point to a gene id which itself points to 2 genes.
+
Query used to find this:
+
[code, sql]
----
-- Find Deletable Links
WITH
  -- Comment link data for comments which have related
  -- stable id links and belong to the specified project
  --
  -- Returns 3942 rows
  comments AS (
    SELECT
      a.comment_id
    , a.stable_id
    , a.comment_stable_id
    FROM
      userlogins5.commentstableid@rm38488.login_comment a
      INNER JOIN userlogins5.comments@rm38488.login_comment b
        ON a.comment_id = b.comment_id
    WHERE
      b.project_name = 'PlasmoDB'
  )

  -- Comment data joined to gene data based on the linked
  -- gene id matching an id in the app db geneid table.
  --
  -- NOTE: This query will exclude comment-to-gene links
  --   that have an invalid gene id.
  --
  -- Returns 3867 rows (less because excludes invalid ids)
  , cross_join AS (
    SELECT
      co.comment_id
    , co.comment_stable_id
    , gi.database_name
    , gi.gene
    FROM
      comments co
      INNER JOIN apidbtuning.geneid gi
        ON co.stable_id = gi.id
  )

  -- Select the most recent link per gene per comment to
  -- exclude from the link deletion list.
  --
  -- Returns 3494 rows (less because excludes duplicate links)
  , most_recent AS (
    SELECT
      comment_id
    , gene
    , max(comment_stable_id) AS comment_stable_id
    FROM
      cross_join
    GROUP BY
      comment_id
    , gene
  )

SELECT -- 3867 Rows
  comment_stable_id
  , COUNT(1)
  , LISTAGG(gene, ', ') WITHIN GROUP ( ORDER BY gene )
FROM
  cross_join
GROUP BY comment_stable_id
HAVING COUNT(1) > 1
-- MINUS
-- SELECT -- 3494 rows
--   comment_stable_id
-- FROM
--   most_recent
;
----

14:15::

Asked Steve what the expected behavior should be, and also
how we should handle the complication where by selecting the
latest link (as inserted by the tuning manager) we may
accidentally remove a comment from a gene altogether,
assuming the tuning manager inserts 2 link records when an
old gene record is split