= User comment cleanup
:toc:
:toclevels: 3
:sectnums:
:source-highlighter: pygments
:icons: font
:curDir: /upenn/By-Task/comment-process-fix
ifdef::env-github[]
:warning-caption: ⚠
:note-caption: ❕
endif::[]

== Questions / Concerns

* [x] Code around sequences from table names?
  ** This will also mean updating the pk sequences since our
    code uses the table name to generate the sequence names
    for lookup.
* [x] Will the triggers need to be updated?
  ** Triggers will be removed
* [x] What is `cmntRef_trggr_pkg`?
  ** This is a custom package that will need to be removed.
* [ ] Migration script?
* [x] Should all the comment tables have a `comment_` prefix? +
  (`locations`, `targetcategory`, `review_status`)
  ** [x] Steve says these should be prefixed, however this will
    will create a conflict with the existing `commenttargetcategory`
    *** Steve says `comment_comment_target_category`
    table.  This needs to be resolved.
* [x] What is the use case for keeping the `comment_stable_id`
  column on the `commentstableid` table?  The table is just
  a linking table at this point and i don't think the links
  themselves will need identifiers?
  ** Steve says no need for a pk in a joining table
* [ ] What about the `comment.location_string` column? That
  data should exist in the locations table.
  link:{curDir}/search/comments.location_string.txt[External References].


== Tables / Views


=== `comments` Table


==== Drop the `comments.stable_id` column

link:{curDir}/search/comments.stable_id.txt[External References]

[source, sql]
----
ALTER TABLE userlogins5.comments
DROP COLUMN stable_id;
----


==== Rename `comments.comment_target_id`

link:{curDir}/search/comments.comment_target_id.txt[External References]

[source, sql]
----
ALTER TABLE userlogins5.comments
RENAME COLUMN comment_target_id TO comment_target_type;
----


=== `commentfile` Table


==== Rename `commentfile` table

link:{curDir}/search/commentfile.txt[External References]

[source, sql]
----
RENAME userlogins5.commentfile TO comment_file;
RENAME userlogins5.commentfile_idx01 TO comment_file_idx01;
RENAME userlogins5.commentfile_pkseq TO comment_file_pkseq;
----


=== `commentreference` Table


==== Rename `commentreference` table

link:{curDir}/search/commentreference.txt[External References]

[source, sql]
----
RENAME userlogins5.commentreference TO comment_reference;
RENAME userlogins5.commentreference_idx01 TO comment_reference_idx01;
RENAME userlogins5.commentreference_idx02 TO comment_reference_idx02;
RENAME userlogins5.commentreference_pkseq TO comment_reference_pkseq;
----


=== `commentsequence` Table


==== Rename `commentsequence` table

link:{curDir}/search/commentsequence.txt[External References]

[source, sql]
----
RENAME userlogins5.commentsequence TO comment_sequence;
RENAME userlogins5.commentsequence_idx01 TO comment_sequence_idx01;
RENAME userlogins5.commentsequence_pkseq TO comment_sequence_pkseq;
----


=== `commentstableid` Table


==== Rename `commentstableid` table

link:{curDir}/search/commentstableid.txt[External References]

[source, sql]
----
RENAME userlogins5.commentstableid TO comment_target;
RENAME userlogins5.commentstableid_idx01 TO comment_target_idx01;
RENAME userlogins5.commentstableid_ux01 TO comment_target_ux01;
RENAME userlogins5.commentstableid_pkseq TO comment_target_pkseq;
----


==== Add `is_primary_target` Column

[source, sql]
----
ALTER TABLE userlogins5.comment_target
ADD is_primary_target NUMBER(1) DEFAULT 0 NOT NULL;
----


==== Rename `stable_id` column

link:{curDir}/search/commentstableid.stable_id.txt[External References]

[source, sql]
----
ALTER TABLE userlogins5.comment_target
RENAME COLUMN stable_id TO target_id;
----


==== Drop `comment_stable_id`

link:{curDir}/search/commentstableid.comment_stable_id.txt[External References]

[source, sql]
----
ALTER TABLE userlogins5.comment_target
DROP COLUMN comment_stable_id;
----


==== Create new column Constraints

Creates a unique index on the comment id value for records
that have the `is_primary_target` flag set to `1`.

Slightly roundabout way to make sure a comment can only have
one primary target link without having to create triggers or
functions.

[source, sql]
----
CREATE UNIQUE INDEX comment_target_id_one_primary
ON userlogins5.comment_target (
  CASE
    WHEN is_primary_target = 1
    THEN comment_id
    ELSE NULL
  END
);
----


==== Cleanup comment link conflicts

There will likely be some junk records in the related record
table that will cause conflicts when trying to copy over the
comment targets.

[source, sql]
----
DELETE FROM
  userlogins5.comment_target
WHERE
  (comment_id, stable_id) IN (
    SELECT comment_id, stable_id
    FROM userlogins5.comments
  );
----


==== Insert primary comment targets

[source, sql]
----
INSERT INTO
  userlogins5.comment_target (
    comment_target_link_id
  , target_id
  , comment_id
  , is_primary_target
)
SELECT
  (SELECT userlogins5.commentstableid_pkseq.nextval FROM dual)
, stable_id
, comment_id
, 1
FROM
  userlogins5.comments
----


=== `commenttargetcategory` Table

NOTE: All columns in this table are currently indexed and
  this will still be the case after all the changes below.
  Not sure if we view that as a problem.

==== Rename `commenttargetcategory` table

link:{curDir}/search/commenttargetcategory.txt[External References]

[source, sql]
----
RENAME userlogins5.commenttargetcategory TO comment_comment_target_category;
RENAME userlogins5.commenttargetcategory_idx01 TO comment_comment_target_category_idx01;
RENAME userlogins5.commenttargetcategory_idx02 TO comment_comment_target_category_idx02;
----


==== Drop `commenttargetcategory_pkseq` Sequence

link:{curDir}/search/commenttargetcategory_pkseq.txt[External References]

[source, sql]
----
DROP SEQUENCE userlogins5.commentTargetCategory_pkseq;
----


==== Drop `comment_target_category_id` Column

Column is not used for anything other than inserts.

link:{curDir}/search/commenttargetcategory.comment_target_category_id.txt[External References]

[source, sql]
----
ALTER TABLE userlogins5.comment_comment_target_category
DROP COLUMN comment_target_category_id;
----


==== Rename `target_category_id` Column

link:{curDir}/search/commenttargetcategory.target_category_id.txt[External References]

[source, sql]
----
ALTER TABLE userlogins5.comment_comment_target_category
RENAME COLUMN target_category_id TO comment_target_category_id.
----


=== `comment_target` Table


==== Rename `comment_target` table

link:{curDir}/search/comment_target.txt[External References]

[source, sql]
----
RENAME userlogins5.comment_target TO comment_target_type;
----


==== Cleanup dead data

[source, sql]
----
DELETE FROM userlogins5.comment_target_type
WHERE comment_target_type_id IN ('protein', 'phenotype');
----


==== Insert missing target types

[source, sql]
----
INSERT INTO
  userlogins5.comment_target_type (
    comment_target_type_id
  , comment_target_type_name
  , require_location
  )
VALUES
  ('snp',      'SNP',      0)
, ('est',      'EST',      0)
, ('assembly', 'Assembly', 0)
, ('sage',     'Sage',     0)
, ('orf',      'ORF',      0)
----


=== `categories` Table


==== Drop `categories` Table

link:{curDir}/search/categories.txt[External References]

[source, sql]
----
DROP TABLE userlogins5.categories; 
----


=== `targetcategory` Table


==== Rename to `comment_target_category`

WARNING: TODO: references to this?

[source, sql]
----
RENAME userlogins5.targetcategory TO comment_target_category;
----


==== Rename `comment_target_id` column

WARNING: TODO: References?

[source, sql]
----
ALTER TABLE userlogins5.target_category
  RENAME COLUMN comment_target_id TO comment_target_type;
----


==== Add foreign key to `comment_target_type`

[source, sql]
----
ALTER TABLE userlogins5.target_category
  ADD CONSTRAINT comment_target_type_ref_fkey
  FOREIGN KEY (comment_target_id)
  REFERENCES userlogins5.comment_target_type (comment_target_type);
----


=== `mappedcomment` View


== Trigger / Function / Package Cleanup

Remove the following:

----
OWNER	TRIGGER_NAME
USERLOGINS5	COMMENTS_UPDATE
USERLOGINS5	COMMENTS_DELETE
USERLOGINS5	COMMENTS_INSERT
USERLOGINS5	CSI_INSERT
USERLOGINS5	CSI_DELETE
USERLOGINS5	CSI_UPDATE
USERLOGINS5	CMNTREF_MARKUPDATEDID
USERLOGINS5	CMNTREF_SETUP
USERLOGINS5	CMNTREF_MARKINSERTEDID
USERLOGINS5	CMNTREF_UPDATETSC
USERLOGINS5	CMNTREF_MARKDELETEDID
USERLOGINS5	COMMENTUSERS_UPDATE
----


=== Packages


==== `cmntRef_trggr_pkg`

.External References
[cols=">1,8,2", options="header"]
|====
| Usages | File                      | Actions
| 14     | createCommentTriggers.sql |
|====


== Misc / Followup

. Fix the mapped comments view
. Rework queries from original task?


== Sequence

. <<Drop `categories` Table>>
. <<Rename `commentfile` table>>
. <<Rename `commentreference` table>>
. <<Rename `commentsequence` table>>
. <<Rename `commenttargetcategory` table>>
. <<Rename `comment_target` table>>
. <<Add `is_primary_target` Column>>
. <<Cleanup comment link conflicts>>
. <<Insert primary comment targets>>
. <<Drop the `comments.stable_id` column>>
. <<Insert missing target types>>