= User comment cleanup
:toc:
:toclevels: 3
:sectnums:
:source-highlighter: pygments
:icons: font
:curDir: /upenn/By-Task/comment-process-fix
ifdef::env-github[]
:warning-caption: ⚠
endif::[]

== Questions / Concerns

. Code around sequences from table names?
.. This will also mean updating the pk sequences since our
   code uses the table name to generate the sequence names
   for lookup.
. Will the triggers need to be updated?
.. Triggers will be removed
. What is `cmntRef_trggr_pkg`?
.. This is a custom package that will need to be removed.
. Migration script?
. Should all the comment tables have a `comment_` prefix? +
  (`locations`, `targetcategory`, `review_status`)

== Tables

=== `comments`

==== Drop the `comments.stable_id` column

link:{curDir}/search/comments.stable_id.txt[External References]

[source, sql]
----
ALTER TABLE userlogins5.comments
DROP COLUMN stable_id;
----

==== Rename `comments.comment_target_id`

link:{curDir}/search/comments.comment_target_id.txt[External References]

[source, sql]
----
ALTER TABLE userlogins5.comments
RENAME COLUMN comment_target_id TO comment_target_type;
----

=== `commentfile`

==== Rename to `comment_file`

link:{curDir}/search/commentfile.txt[External References]

[source, sql]
----
RENAME userlogins5.commentfile TO comment_file;
RENAME userlogins5.commentfile_idx01 TO comment_file_idx01;
RENAME userlogins5.commentfile_pkseq TO comment_file_pkseq;
----

=== `commentreference`

==== Rename to `comment_reference`

link:{curDir}/search/commentreference.txt[External References]

[source, sql]
----
RENAME userlogins5.commentreference TO comment_reference;
RENAME userlogins5.commentreference_idx01 TO comment_reference_idx01;
RENAME userlogins5.commentreference_idx02 TO comment_reference_idx02;
RENAME userlogins5.commentreference_pkseq TO comment_reference_pkseq;
----

=== `commentsequence`

==== Rename to `comment_sequence`

link:{curDir}/search/commentsequence.txt[External References]

[source, sql]
----
RENAME userlogins5.commentsequence TO comment_sequence;
RENAME userlogins5.commentsequence_idx01 TO comment_sequence_idx01;
RENAME userlogins5.commentsequence_pkseq TO comment_sequence_pkseq;
----

=== `commentstableid`

==== Rename to `comment_target_id`

link:{curDir}/search/commentstableid.txt[External References]

[source, sql]
----
RENAME userlogins5.commentstableid TO comment_target_id;
RENAME userlogins5.commentstableid_idx01 TO comment_target_id_idx01;
RENAME userlogins5.commentstableid_ux01 TO comment_target_id_ux01;
RENAME userlogins5.commentstableid_pkseq TO comment_target_id_pkseq;
----

==== Add `is_primary_target` Column

[source, sql]
----
ALTER TABLE userlogins5.commentstableid
ADD is_primary_target NUMBER(1) DEFAULT 0 NOT NULL;
----

==== Create new column Constraints

Creates a unique index on the comment id value for records
that have the `is_primary_target` flag set to `1`.

Slightly roundabout way to make sure a comment can only have
one primary target link without having to create triggers or
functions.

[source, sql]
----
CREATE UNIQUE INDEX comment_target_id_one_primary
ON userlogins5.commentstableid (
  CASE
    WHEN is_primary_target = 1
    THEN comment_id
    ELSE NULL
  END
);
----

==== Cleanup comment link conflicts

There will likely be some junk records in the related record
table that will cause conflicts when trying to copy over the
comment targets.

[source, sql]
----
DELETE FROM
  userlogins5.commentstableid
WHERE
  (comment_id, stable_id) IN (
    SELECT comment_id, stable_id
    FROM userlogins5.comments
  );
----

==== Insert primary comment targets

[source, sql]
----
INSERT INTO
  userlogins5.commentstableid (
    comment_stable_id
  , stable_id
  , comment_id
  , is_primary_target
)
SELECT
  (SELECT userlogins5.commentstableid_pkseq.nextval FROM dual)
, stable_id
, comment_id
, 1
FROM
  userlogins5.comments
----


=== `commenttargetcategory`

==== Rename to `comment_target_category`

link:{curDir}/search/commenttargetcategory.txt[External References]

[source, sql]
----
RENAME userlogins5.commenttargetcategory TO comment_target_category;
RENAME userlogins5.commenttargetcategory_idx01 TO comment_target_category_idx01;
RENAME userlogins5.commenttargetcategory_idx02 TO comment_target_category_idx02;
RENAME userlogins5.commenttargetcategory_pkseq TO comment_target_category_pkseq;
----

=== `comment_target`

==== Rename to `comment_target_type`

link:{curDir}/search/comment_target.txt[External References]

[source, sql]
----
RENAME userlogins5.comment_target TO comment_target_type;
----

==== Cleanup dead data

[source, sql]
----
DELETE FROM userlogins5.comment_target_type
WHERE comment_target_type_id IN ('protein', 'phenotype');
----

==== Insert missing target types

[source, sql]
----
INSERT INTO
  userlogins5.comment_target_type (
    comment_target_type_id
  , comment_target_type_name
  , require_location
  )
VALUES
  ('snp',      'SNP',      0)
, ('est',      'EST',      0)
, ('assembly', 'Assembly', 0)
, ('sage',     'Sage',     0)
, ('orf',      'ORF',      0)
----

=== `categories`

==== Drop Table

link:{curDir}/search/categories.txt[External References]

[source, sql]
----
DROP TABLE userlogins5.categories; 
----

=== `targetcategory`

==== Rename to `target_category`

WARNING: TODO: references to this?

[source, sql]
----
RENAME userlogins5.targetcategory TO target_category;
----

==== Rename `comment_target_id` column

[source, sql]
----
ALTER TABLE userlogins5.target_category
  RENAME COLUMN comment_target_id TO comment_target_type;
----

==== Add foreign key to `comment_target_type`

[source, sql]
----
ALTER TABLE userlogins5.target_category
  ADD CONSTRAINT comment_target_type_ref_fkey
  FOREIGN KEY (comment_target_id)
  REFERENCES userlogins5.comment_target_type (comment_target_type);
----

== Trigger / Function / Package Cleanup

Remove the following:

----
OWNER	TRIGGER_NAME
USERLOGINS5	COMMENTS_UPDATE
USERLOGINS5	COMMENTS_DELETE
USERLOGINS5	COMMENTS_INSERT
USERLOGINS5	CSI_INSERT
USERLOGINS5	CSI_DELETE
USERLOGINS5	CSI_UPDATE
USERLOGINS5	CMNTREF_MARKUPDATEDID
USERLOGINS5	CMNTREF_SETUP
USERLOGINS5	CMNTREF_MARKINSERTEDID
USERLOGINS5	CMNTREF_UPDATETSC
USERLOGINS5	CMNTREF_MARKDELETEDID
USERLOGINS5	COMMENTUSERS_UPDATE
----

=== Packages

==== `cmntRef_trggr_pkg`

.External References
[cols=">1,8,2", options="header"]
|====
| Usages | File                      | Actions
| 14     | createCommentTriggers.sql |
|====


== Misc / Followup

. Fix the mapped comments view
. Copy targets from comment table to linking table
. Rework queries from original task?

== Sequence

. <<Add `is_primary_target` Column>>
. <<Cleanup comment link conflicts>>
. <<Insert primary comment targets>>
. <<Drop the `comments.stable_id` column>>
. <<Insert missing target types>>