= User comment cleanup
:toc:
:toclevels: 3
:sectnums:
:source-highlighter: pygments
:icons: font
ifdef::env-github[]
:warning-caption: âš 
:note-caption: â•
:tip-caption: ðŸ’¡
endif::[]
:curDir: /upenn/By-Task/comment-process-fix

== Questions / Concerns

* [x] Code around sequences from table names?
  ** This will also mean updating the pk sequences since our
    code uses the table name to generate the sequence names
    for lookup.
* [x] Will the triggers need to be updated?
  ** Triggers will be removed
* [x] What is `cmntRef_trggr_pkg`?
  ** This is a custom package that will need to be removed.
* [ ] Migration script?
* [x] Should all the comment tables have a `comment_` prefix? +
  (`locations`, `targetcategory`, `review_status`)
  ** [x] Steve says these should be prefixed, however this will
    will create a conflict with the existing `commenttargetcategory`
    *** Steve says `comment_comment_target_category`
    table.  This needs to be resolved.
* [x] What is the use case for keeping the `comment_stable_id`
  column on the `commentstableid` table?  The table is just
  a linking table at this point and i don't think the links
  themselves will need identifiers?
  ** Steve says no need for a pk in a joining table
* [ ] What about the `comment.location_string` column? That
  data should exist in the locations table.
  link:{curDir}/search/comments.location_string.txt[External References].


== `comments` Table


=== Drop the `comments.stable_id` column

link:{curDir}/search/comments.stable_id.txt[External References]

[source, sql]
----
ALTER TABLE userlogins5.comments
  DROP COLUMN stable_id;
----


=== Rename `comments.comment_target_id`

link:{curDir}/search/comments.comment_target_id.txt[External References]

[source, sql]
----
ALTER TABLE comments
  RENAME COLUMN comment_target_id TO comment_target_type;
----


== Comment to File Table


=== Rename `commentfile` table

link:{curDir}/search/commentfile.txt[External References]

[source, sql]
ALTER TABLE userlogins5.commentfile
  RENAME TO comment_file;


=== Rename Comment to File Indices

[WARNING]
.Remaining TODOs
====
* [ ] Find References
====

[source, sql]
ALTER INDEX userlogins5.commentfile_idx01
  RENAME TO comment_file_idx01;


=== Recreate Sequence `commentfile_pkseq`

[WARNING]
.Remaining TODOs
====
* [ ] Find References
* [ ] Is this sequence/pkey actually needed?
* [x] Find the actual increment value
====

[source, sql]
----
DECLARE
  seq_start NUMBER;
BEGIN
  SELECT userlogins5.commentfile_pkseq.nextval INTO seq_start FROM dual;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE userlogins5.comment_file_pkseq START WITH ' || seq_start || ' INCREMENT BY 1';
END;

DROP SEQUENCE userlogins5.commentfile_pkseq;

GRANT SELECT ON userlogins5.comment_file_pkseq TO GUS_W;
GRANT SELECT ON userlogins5.comment_file_pkseq TO GUS_R;
----


== Comment to Reference Table


=== Rename `commentreference` table

link:{curDir}/search/commentreference.txt[External References]

[source, sql]
ALTER TABLE userlogins5.commentreference
  RENAME TO comment_reference;


=== Rename Comment Reference Indices

[WARNING]
.Remaining TODOs
====
* [ ] Find References
====

[source, sql]
----
ALTER INDEX userlogins5.commentreference_idx01
  RENAME TO comment_reference_idx01;

ALTER INDEX userlogins5.commentreference_idx02
  RENAME TO comment_reference_idx02;
----


=== Recreate Sequence `commentreference_pkseq`

[WARNING]
.Remaining TODOs
====
* [ ] Find References
* [ ] Is the pkey/sequence needed on this table?
* [ ] Lookup actual increment value for sequence
====

[source, sql]
----
DECLARE
  seq_start NUMBER;
BEGIN
  SELECT userlogins5.commentreference_pkseq.nextval INTO seq_start FROM dual;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE userlogins5.comment_reference_pkseq START WITH ' || seq_start || ' INCREMENT BY 1';
END;

DROP SEQUENCE userlogins5.commentreference_pkseq;

GRANT SELECT ON userlogins5.comment_reference_pkseq TO GUS_W;
GRANT SELECT ON userlogins5.comment_reference_pkseq TO GUS_R;
----


== Comment to Sequence Table


=== Rename `commentsequence` table

link:{curDir}/search/commentsequence.txt[External References]

[source, sql]
ALTER TABLE userlogins5.commentsequence
  RENAME TO comment_sequence;


=== Rename Comment to Sequence Indices

[WARNING]
.Remaining TODOs
====
* [ ] Find References
====

[source, sql]
ALTER INDEX userlogins5.commentsequence_idx01
  RENAME TO comment_sequence_idx01;


=== Recreate Sequence `commentsequence_pkseq`

[WARNING]
.Remaining TODOs
====
* [ ] Find References
* [ ] Is this sequence / pkey even needed?
* [ ] Find actual increment value
====

[source, sql]
----
DECLARE
  seq_start NUMBER;
BEGIN
  SELECT userlogins5.commentsequence_pkseq.nextval INTO seq_start FROM dual;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE userlogins5.comment_sequence_pkseq START WITH ' || seq_start || ' INCREMENT BY 1';
END;

DROP SEQUENCE userlogins5.commentsequence_pkseq;

GRANT SELECT ON userlogins5.comment_sequence_pkseq TO GUS_W;
GRANT SELECT ON userlogins5.comment_sequence_pkseq TO GUS_R;
----


== Comment to Comment Target Table


=== Rename `commentstableid` table

link:{curDir}/search/commentstableid.txt[External References]

[source, sql]
ALTER TABLE commentstableid
  RENAME TO comment_target;


=== Rename Comment to Comment Target Indices

[WARNING]
.Remaining TODOs
====
* [ ] Find references
====

[source, sql]
----
ALTER INDEX commentstableid_idx01
  RENAME TO comment_target_idx01;

ALTER INDEX commentstableid_ux01
  RENAME TO comment_target_ux01;
----


=== Drop Comment to Comment Target Primary Key Column

link:{curDir}/search/commentstableid.comment_stable_id.txt[External References]

[source, sql]
ALTER TABLE userlogins5.comment_target
  DROP COLUMN comment_stable_id;


=== Remove Sequence `commentstableid_pkseq`

[WARNING]
.Remaining TODOs
====
* [ ] Find references
====

[source, sql]
DROP SEQUENCE userlogins5.commentstableid_pkseq;



=== Add `is_primary_target` Column

[source, sql]
ALTER TABLE userlogins5.comment_target
  ADD is_primary_target NUMBER(1) DEFAULT 0 NOT NULL;


=== Rename `stable_id` column

link:{curDir}/search/commentstableid.stable_id.txt[External References]

[source, sql]
ALTER TABLE userlogins5.comment_target
  RENAME COLUMN stable_id TO target_id;


=== Create new column Constraints

Creates a unique index on the comment id value for records
that have the `is_primary_target` flag set to `1`.

Slightly roundabout way to make sure a comment can only have
one primary target link without having to create triggers or
functions.

[source, sql]
----
CREATE UNIQUE INDEX comment_target_id_one_primary
ON userlogins5.comment_target (
  CASE
    WHEN is_primary_target = 1
    THEN comment_id
    ELSE NULL
  END
);
----


=== Cleanup comment link conflicts

There will likely be some junk records in the related record
table that will cause conflicts when trying to copy over the
comment targets.

[source, sql]
----
DELETE FROM
  userlogins5.comment_target
WHERE
  (comment_id, target_id) IN (
    SELECT comment_id, stable_id
    FROM userlogins5.comments
  )
;
----


=== Insert primary comment targets

[source, sql]
----
INSERT INTO
  userlogins5.comment_target (
    target_id
  , comment_id
  , is_primary_target
)
SELECT
  stable_id
, comment_id
, 1
FROM
  userlogins5.comments
;
----


== Comment to Comment Target Category Table


=== Rename Table `commenttargetcategory`

link:{curDir}/search/commenttargetcategory.txt[External References]

[source, sql]
ALTER TABLE commenttargetcategory
  RENAME TO comment_comment_target_category;


=== Rename Comment to Comment Target Category Indices

[source, sql]
----
ALTER INDEX commenttargetcategory_idx01
  RENAME TO comment_comment_target_category_idx01;

ALTER INDEX commenttargetcategory_idx02
  RENAME TO comment_comment_target_category_idx02;
----


=== Drop `commenttargetcategory_pkseq` Sequence

link:{curDir}/search/commenttargetcategory_pkseq.txt[External References]

[source, sql]
DROP SEQUENCE commentTargetCategory_pkseq;


=== Drop `comment_target_category_id` Column

Column is not used for anything other than inserts.

link:{curDir}/search/commenttargetcategory.comment_target_category_id.txt[External References]

[source, sql]
ALTER TABLE comment_comment_target_category
  DROP COLUMN comment_target_category_id;


=== Rename `target_category_id` Column

link:{curDir}/search/commenttargetcategory.target_category_id.txt[External References]

[source, sql]
ALTER TABLE comment_comment_target_category
  RENAME COLUMN target_category_id TO comment_target_category_id;


== `comment_target` Table


=== Rename `comment_target` table

link:{curDir}/search/comment_target.txt[External References]

[source, sql]
----
RENAME userlogins5.comment_target TO comment_target_type;
----


=== Rename `comment_target_id` column

[source, sql]
----
ALTER TABLE comment_target_type
  RENAME COLUMN comment_target_id TO comment_target_type_id;
----


=== Rename `comment_target_name` column

[source, sql]
----
ALTER TABLE comment_target_type
  RENAME COLUMN comment_target_name TO comment_target_type_name;
----


=== Cleanup dead data

[source, sql]
----
DELETE FROM userlogins5.comment_target_type
  WHERE comment_target_type_id IN ('protein', 'phenotype');
----


=== Insert missing target types

[source, sql]
----
INSERT INTO comment_target_type (comment_target_type_id, comment_target_type_name, require_location)
  VALUES ('snp', 'SNP', 0);
INSERT INTO comment_target_type (comment_target_type_id, comment_target_type_name, require_location)
  VALUES ('est', 'EST', 0);
INSERT INTO comment_target_type (comment_target_type_id, comment_target_type_name, require_location)
  VALUES ('assembly', 'Assembly', 0);
INSERT INTO comment_target_type (comment_target_type_id, comment_target_type_name, require_location)
  VALUES ('sage', 'Sage', 0);
INSERT INTO comment_target_type (comment_target_type_id, comment_target_type_name, require_location)
  VALUES ('orf', 'ORF', 0);
----


== `categories` Table


=== Drop `categories` Table

link:{curDir}/search/categories.txt[External References]

[source, sql]
----
DROP TABLE userlogins5.categories; 
----


== `targetcategory` Table


=== Rename `targetcategory` table

WARNING: TODO: references to this?

[source, sql]
----
ALTER TABLE userlogins5.targetcategory
  RENAME TO comment_target_category;
----


=== Rename `target_category_id` column

WARNING: TODO: References?

[source, sql]
----
ALTER TABLE userlogins5.comment_target_category
  RENAME COLUMN target_category_id TO comment_target_category_id;
----


=== Rename `comment_target_id` column

[source, sql]
----
ALTER TABLE userlogins5.comment_target_category
  RENAME COLUMN comment_target_id TO comment_target_type;
----


=== Add foreign key to `comment_target_type`

[source, sql]
----
ALTER TABLE userlogins5.comment_target_category
  ADD CONSTRAINT comment_target_type_ref_fkey
  FOREIGN KEY (comment_target_type)
  REFERENCES userlogins5.comment_target_type (comment_target_type_id);
----


== `mappedcomment` View

[source, sql]
----
CREATE OR REPLACE VIEW userlogins5.mappedcomment AS
  SELECT
    c.comment_id
  , c.user_id
  , c.email
  , c.comment_date
  , c.comment_target_id
  , t.stable_id
  , c.conceptual
  , c.project_name
  , c.project_version
  , c.headline
  , c.review_status_id
  , c.accepted_version
  , c.location_string
  , c.organism
  , c.is_visible
  FROM
    userlogins5.comments c
    LEFT JOIN userlogins5.commentstableid t
      ON c.comment_id = t.comment_id
;
----

== Trigger / Function / Package Cleanup

Remove the following:

----
OWNER	TRIGGER_NAME
USERLOGINS5	COMMENTS_UPDATE
USERLOGINS5	COMMENTS_DELETE
USERLOGINS5	COMMENTS_INSERT
DROP TRIGGER userlogins5.csi_insert;
DROP TRIGGER userlogins5.csi_delete;
DROP TRIGGER userlogins5.csi_update;
USERLOGINS5	CMNTREF_MARKUPDATEDID
USERLOGINS5	CMNTREF_SETUP
USERLOGINS5	CMNTREF_MARKINSERTEDID
USERLOGINS5	CMNTREF_UPDATETSC
USERLOGINS5	CMNTREF_MARKDELETEDID
USERLOGINS5	COMMENTUSERS_UPDATE
----


=== Packages


==== `cmntRef_trggr_pkg`

.External References
[cols=">1,8,2", options="header"]
|====
| Usages | File                      | Actions
| 14     | createCommentTriggers.sql |
|====


== Misc / Followup

. Fix the mapped comments view
. Rework queries from original task?


== Sequence

. <<Drop `categories` Table>>
. <<Rename `targetcategory` table>>
. <<Add `is_primary_target` Column>>
. <<Cleanup comment link conflicts>>
. <<Insert primary comment targets>>
. <<Drop the `comments.stable_id` column>>
. <<Insert missing target types>>