= User comment cleanup
:toc:
:toclevels: 3
:sectnums:
:source-highlighter: pygments
:icons: font
:curDir: /upenn/By-Task/comment-process-fix

== Table Cleanup

=== Questions / Concerns

. This will also mean updating the pk sequences since our
  code uses the table name to generate the sequence names
  for lookup.
. Will the triggers need to be updated?
.. Triggers will be removed
. What is `cmntRef_trggr_pkg.stale(i)`?
. What is `cmntRef_trggr_pkg.empty`

=== Tables

==== `commentfile`

link:{curDir}/csv/commentfile.csv[External References]

===== Rename to `comment_file`

[source, sql]
----
RENAME userlogins5.commentfile TO comment_file;
RENAME userlogins5.commentfile_idx01 TO comment_file_idx01;
RENAME userlogins5.commentfile_pkseq TO comment_file_pkseq;
----

==== `commentreference`

link:{curDir}/csv/commentreference.csv[External References]

===== Rename to `comment_reference`

[source, sql]
----
RENAME userlogins5.commentreference TO comment_reference;
RENAME userlogins5.commentreference_idx01 TO comment_reference_idx01;
RENAME userlogins5.commentreference_idx02 TO comment_reference_idx02;
RENAME userlogins5.commentreference_pkseq TO comment_reference_pkseq;
----

==== `commentsequence`

link:{curDir}/csv/commentsequence.csv[External References]

===== Rename to `comment_sequence`

[source, sql]
----
RENAME userlogins5.commentsequence TO comment_sequence;
RENAME userlogins5.commentsequence_idx01 TO comment_sequence_idx01;
RENAME userlogins5.commentsequence_pkseq TO comment_sequence_pkseq;
----

==== `commentstableid`

link:{curDir}/csv/commentstableid.csv[External References]

===== Rename to `comment_target_id`

[source, sql]
----
RENAME userlogins5.commentstableid TO comment_target_id;
RENAME userlogins5.commentstableid_idx01 TO comment_target_id_idx01;
RENAME userlogins5.commentstableid_ux01 TO comment_target_id_ux01;
RENAME userlogins5.commentstableid_pkseq TO comment_target_id_pkseq;
----

==== `commenttargetcategory`

link:{curDir}/csv/commenttargetcategory.csv[External References]

===== Rename to `comment_target_category`

[source, sql]
----
RENAME userlogins5.commenttargetcategory TO comment_target_category;
RENAME userlogins5.commenttargetcategory_idx01 TO comment_target_category_idx01;
RENAME userlogins5.commenttargetcategory_idx02 TO comment_target_category_idx02;
RENAME userlogins5.commenttargetcategory_pkseq TO comment_target_category_pkseq;
----

==== `comment_target`

link:{curDir}/csv/comment_target.csv[External References]

===== Rename to `comment_target_type`

[source, sql]
----
RENAME userlogins5.comment_target TO comment_target_type;
----

==== `categories`

link:{curDir}/csv/categories.csv[External References]

===== Drop Table

[source, sql]
----
DROP TABLE userlogins5.categories; 
----

== Column Cleanup

=== `comments` Table

==== Drop the `comments.stable_id` column

[source, sql]
----
ALTER TABLE userlogins5.comments
DROP COLUMN stable_id;
----

===== Code References

[cols=">1,8,2", options="header"]
|====
| Usages | File                      | Actions
| 10     | apiTuningManager.xml      |
| 1      | BaseCommentQuery.java     |
| 2      | Column.java               |
| 22     | commentTableQueries.xml   |
| 3      | FindCommentQuery.java     |
| 2      | geneAttributeQueries.xml  |
| 5      | geneQueries.xml           |
| 1      | generateGeneMetrics       |
| 1      | generateGeneMetrics_New   |
| 2      | geneRecord.xml            |
| 7      | geneTableQueries.xml      |
| 1      | genomicRecords.xml        |
| 2      | GetCommentQuery.java      |
| 1      | InsertCommentQuery.java   |
| 1      | InsertStableIdQuery.java  |
| 4      | MigrateCommentsMapper.xml |
| 4      | migration_comment_b21.sql |
| 1      | popsetRecords.xml         |
| 6      | showComments.jsp          |
| 1      | showNewCommentLinks       |
|====


==== Rename `comments.comment_target_id`

[source, sql]
----
ALTER TABLE userlogins5.comments
RENAME COLUMN comment_target_id TO comment_target_type;
----

===== Code References

[cols=">1,8,2", options="header"]
|====
| Usages | File                        | Actions
| 2      | apiTuningManager.xml        |
| 2      | Column.java                 |
| 1      | commentTableQueries.xml     |
| 2      | geneRecord.xml              |
| 2      | geneTableQueries.xml        |
| 1      | genomicRecords.xml          |
| 1      | InsertCommentQuery.java     |
| 1      | KeywordSearchPlugin.java    |
| 6      | MigrateCommentsMapper.xml   |
| 6      | migration_comment_b21.sql   |
| 1      | popsetRecords.xml           |
| 3      | showComments.jsp            |
| 1      | TranscriptSearchPlugin.java |
|====

=== `commentstableid` Table

==== Add `is_primary_target` Column

===== Create Column

[source, sql]
----
ALTER TABLE userlogins5.commentstableid
ADD is_primary_target NUMBER(1) DEFAULT 0 NOT NULL;
----

===== Create Constraints

Creates a unique index on the comment id value for records
that have the `is_primary_target` flag set to `1`.

Slightly roundabout way to make sure a comment can only have
one primary target link without having to create triggers or
functions.

[source, sql]
----
CREATE UNIQUE INDEX comment_target_id_one_primary
ON userlogins5.commentstableid (
  CASE
    WHEN is_primary_target = 1
    THEN comment_id
    ELSE NULL
  END
);
----

== Data Cleanup

=== Move comment target links

==== Cleanup conflicts

There will likely be some junk records in the related record
table that will cause conflicts when trying to copy over the
comment targets.

[source, sql]
----
DELETE FROM
  userlogins5.commentstableid
WHERE
  (comment_id, stable_id) IN (
    SELECT comment_id, stable_id
    FROM userlogins5.comments
  );
----

==== Copy over targets

[source, sql]
----
INSERT INTO
  userlogins5.commentstableid (
    comment_stable_id
  , stable_id
  , comment_id
  , is_primary_target
)
SELECT
  (SELECT userlogins5.commentstableid_pkseq.nextval FROM dual)
, stable_id
, comment_id
, 1
FROM
  userlogins5.comments
----

=== `comment_target` Table

==== Cleanup dead data

[source, sql]
----
DELETE FROM userlogins5.comment_target_type
WHERE comment_target_type_id IN ('protein', 'phenotype');
----

==== Insert missing data

[source, sql]
----
INSERT INTO
  userlogins5.comment_target_type (
    comment_target_type_id
  , comment_target_type_name
  , require_location
  )
VALUES
  ('snp',      'SNP',      0)
, ('est',      'EST',      0)
, ('assembly', 'Assembly', 0)
, ('sage',     'Sage',     0)
, ('orf',      'ORF',      0)
----

== Trigger / Function / Package Cleanup

Remove the following:

----
OWNER	TRIGGER_NAME
USERLOGINS5	COMMENTS_UPDATE
USERLOGINS5	COMMENTS_DELETE
USERLOGINS5	COMMENTS_INSERT
USERLOGINS5	CSI_INSERT
USERLOGINS5	CSI_DELETE
USERLOGINS5	CSI_UPDATE
USERLOGINS5	CMNTREF_MARKUPDATEDID
USERLOGINS5	CMNTREF_SETUP
USERLOGINS5	CMNTREF_MARKINSERTEDID
USERLOGINS5	CMNTREF_UPDATETSC
USERLOGINS5	CMNTREF_MARKDELETEDID
USERLOGINS5	COMMENTUSERS_UPDATE
----

=== Packages

==== `cmntRef_trggr_pkg`

.External References
[cols=">1,8,2", options="header"]
|====
| Usages | File                      | Actions
| 14     | createCommentTriggers.sql |
|====


== Misc / Followup

. Fix the mapped comments view
. Copy targets from comment table to linking table
. Rework queries from original task?

== Sequence

. <<Add `is_primary_target` Column>>
. <<Move comment target links>>
. <<Drop the `comments.stable_id` column>>